apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.common.name }}-grafana
  labels:
    {{- include "news-feed.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.common.name }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.common.name }}
        app.kubernetes.io/component: grafana
    spec:
      securityContext:
        fsGroup: 472
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.auth.adminUser | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.auth.adminPassword | quote }}
            - name: GF_INSTALL_PLUGINS
              value: ""
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboard-config
              mountPath: /etc/grafana/provisioning/dashboards/default
          resources:
            {{- toYaml .Values.resources.grafana | nindent 12 }}
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: {{ .Values.common.name }}-grafana-pvc
        - name: grafana-datasources
          configMap:
            name: {{ .Values.common.name }}-grafana-datasources
        - name: grafana-dashboards
          configMap:
            name: {{ .Values.common.name }}-grafana-dashboard-provider
        - name: grafana-dashboard-config
          configMap:
            name: {{ .Values.common.name }}-grafana-dashboards
