apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.common.name }}-grafana-datasources
  labels:
    {{- include "news-feed.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ .Values.common.name }}-prometheus:{{ .Values.prometheus.service.port }}
        isDefault: true
        editable: true
