{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.common.name }}-kafka
  labels:
    {{- include "news-feed.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.common.name }}
      app.kubernetes.io/component: kafka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.common.name }}
        app.kubernetes.io/component: kafka
    spec:
      containers:
        - name: kafka
          image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
          imagePullPolicy: {{ .Values.kafka.image.pullPolicy }}
          env:
            - name: KAFKA_BROKER_ID
              value: {{ .Values.kafka.env.KAFKA_BROKER_ID | quote }}
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "{{ .Values.common.name }}-zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://{{ .Values.common.name }}-kafka:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: {{ .Values.kafka.env.KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR | quote }}
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: {{ .Values.kafka.env.KAFKA_AUTO_CREATE_TOPICS_ENABLE | quote }}
          ports:
            - name: kafka
              containerPort: 9092
              protocol: TCP
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
          resources:
            {{- toYaml .Values.resources.kafka | nindent 12 }}
      volumes:
        - name: kafka-data
          {{- if .Values.kafka.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.common.name }}-kafka-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
