{{- if .Values.newsfeed.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "news-feed.fullname" . }}-config
  labels:
    {{- include "news-feed.labels" . | nindent 4 }}
    app.kubernetes.io/component: newsfeed
data:
  config.json: |
    {
      "kafka_address": "{{ .Values.newsfeed.config.kafka_address }}",
      "redis_address": "{{ .Values.newsfeed.config.redis_address }}",
      "mysql_address": "{{ .Values.newsfeed.config.mysql_address }}"
    }
{{- end }}
