apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.common.name }}-prometheus
  labels:
    {{- include "news-feed.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.common.name }}
      app.kubernetes.io/component: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.common.name }}
        app.kubernetes.io/component: prometheus
    spec:
      securityContext:
        fsGroup: 65534
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/tmp/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
          ports:
            - name: web
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-storage
              mountPath: /tmp/prometheus
          resources:
            {{- toYaml .Values.resources.prometheus | nindent 12 }}
      volumes:
        - name: prometheus-config
          configMap:
            name: {{ .Values.common.name }}-prometheus-config
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: {{ .Values.common.name }}-prometheus-pvc
