apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.name }}-prometheus
  labels:
    {{- include "news-feed.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: {{ .Values.common.name }}
    app.kubernetes.io/component: prometheus
