apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.common.name }}-prometheus-config
  labels:
    {{- include "news-feed.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'mysql-exporter'
        static_configs:
          - targets: ['{{ .Values.common.name }}-mysql:9104']
            labels:
              service: 'mysql'

      - job_name: 'redis-exporter'
        static_configs:
          - targets: ['{{ .Values.common.name }}-redis:9121']
            labels:
              service: 'redis'

      - job_name: 'kafka-jmx-exporter'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['{{ .Values.common.name }}-kafka:7071']
            labels:
              service: 'kafka'
              exporter: 'jmx'


