{{- if .Values.timescaledb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.common.name }}-timescaledb
  labels:
    {{- include "news-feed.labels" . | nindent 4 }}
    app.kubernetes.io/component: timescaledb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.common.name }}
      app.kubernetes.io/component: timescaledb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.common.name }}
        app.kubernetes.io/component: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: "{{ .Values.timescaledb.image.repository }}:{{ .Values.timescaledb.image.tag }}"
          imagePullPolicy: {{ .Values.timescaledb.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.timescaledb.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.timescaledb.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.timescaledb.auth.password | quote }}
            - name: POSTGRES_POSTGRES_PASSWORD
              value: {{ .Values.timescaledb.auth.postgresPassword | quote }}
          ports:
            - name: timescaledb
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: timescaledb-data
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.resources.timescaledb | nindent 12 }}
      volumes:
        - name: timescaledb-data
          {{- if .Values.timescaledb.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.common.name }}-timescaledb-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
